# --- DICIONÁRIO MANUAL DE CORREÇÃO (O INPUT FORNECIDO) ---
dicionario_correcao_lemmas <- c(
  "festo" = "festa",
  "$2fe" = "festa",
  "abraco" = "abraca",
  "acho" = "acha",
  "adeu"= "adeus",
  "aguar"="agua",
  "aguo"="agua",
  "alguir"="alguem",
  "almar"= "alma",
  "almo"= "alma",
  "amanho" = "amanha",
  "ameguir"="amigo",
  "amiga"= "amigo",
  "amo"="ama",
  "aonder"="aonde",
  "apaixon"="apaixonar",
  "aso"="asa",
  "atro"="atra",
  "avenidar" ="avenida" ,
  "balado"="balada",
  "bandir"="bandido",
  "beija"="beijo",
  "beir"="beijo",
  "bocar" ="boca" ,
  "boco" ="boca" ,
  "cabeco"="cabeca",
  "cabecar"="cabeca",
  "carto"="carta",
  "cervejar"  ="cerveja",
  "cer" = "ceu" ,
  "chamo"="chama",
  "chancer"="chance",
  "chur"="chuva",
  "chuvo"="chuva",
  "ciumir"="ciume",
  "cinemo" ="cinema",
  "começar"="comecar",
  "conhecar" ="conhecer",
  "conteguir"="contigo",
  "coiso" ="coisa" ,
  "crianco"="crianca",
  "criancar"="crianca",
  "dançar"="dancar",
  "enfir"="enfim",
  "escurar"="escuro",
  "espelhar"="espelho",
  "esperanco"="esperanca",
  "estrado" ="estrada",
  "estrar"="estrada",
  "estrele"="estrela",
  "estrelo" ="estrela",
  "esquino"="esquina",
  "facar" ="faca" ,
  "filher"="filho",
  "fir"="fim",
  "galerar"="galera",
  "galero"="galera",
  "garota"="garotar",
  "garoto"="garotar",
  "historio"= "historia",
  "homer"="homem",
  "hor"="hora",
  "jeger"="jeito",
  "laio"="laia",
  "lair"="laia",
  "lagrimo"="lagrima",
  "lembranco"="lembranca",
  "lir"= "lua",
  "luze"="luz",
  "luzer"="luz",
  "loucuro"="loucura",
  "luo"="lua",
  "magom"="magoa",
  "malar"="mala",
  "manhar" ="manha",
  "manho" ="manha",
  "manio"="mania",
  "mazer"="maria",
  "meder"="medo",
  "mentiro" ="mentira",
  "meninar"="menina",
  "mino"="mina",
  "morenar"="morena",
  "mortar"="morte",
  "ninguir" = "ninguem",
  "noitir" = "noite",
  "oler"="olha",
  "ondo"="onda",
  "ouver"="ouvir",
  "pai"="pair",
  "pazer"="paz",
  "poeiro"="poeira",
  "praio"="praia",
  "prar"="pro",
  "raco"="raca",
  "roso"="rosa",
  "roupo"= "roupa",
  "ruo"="rua",
  "sangar"="sangue",
  "segreder" ="segredo",
  "sombrar"="sombra",
  "tristezo"="tristeza",
  "tra"="tro"
)


# --- APLICAÇÃO DO DICIONÁRIO DE CORREÇÃO ---

# A função recode() usa o dicionário para substituir todos os valores incorretos
letras_anotadas_df <- letras_anotadas_df %>%
  mutate(
    # !!!dicionario_correcao_lemmas instrui o recode a usar as chaves e valores do vetor
    lemma = recode(lemma, !!!dicionario_correcao_lemmas)
  )

cat(paste0("✅ ", length(dicionario_correcao_lemmas), " regras de lemmas aplicadas com sucesso.\n"))


print(palavras_na_dtm)
